/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.validation;

import dk.sdu.mdsd.validation.AbstractMathInterpreterValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MathInterpreterValidator extends AbstractMathInterpreterValidator {
}
