/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiply</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage#getMultiply()
 * @model
 * @generated
 */
public interface Multiply extends MultiplyOrDivide
{
} // Multiply
