/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage#getPlus()
 * @model
 * @generated
 */
public interface Plus extends PlusOrMinus
{
} // Plus
