/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.mathInterpreter.VariableRef#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage#getVariableRef()
 * @model
 * @generated
 */
public interface VariableRef extends Primary
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Variable)
   * @see dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage#getVariableRef_Value()
   * @model
   * @generated
   */
  Variable getValue();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.mathInterpreter.VariableRef#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Variable value);

} // VariableRef
