/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd;

import dk.sdu.mdsd.MathInterpreterStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathInterpreterStandaloneSetup extends MathInterpreterStandaloneSetupGenerated {
  public static void doSetup() {
    new MathInterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
