/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.ui;

import dk.sdu.mdsd.ui.AbstractMathInterpreterUiModule;
import dk.sdu.mdsd.ui.ExpressionsEObjectHoverProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return ExpressionsEObjectHoverProvider.class;
  }
  
  public MathInterpreterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
