/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mdsd.mathinterpreter.ui.internal.MathinterpreterActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathInterpreterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathinterpreterActivator.getInstance().getInjector("dk.sdu.mdsd.MathInterpreter");
	}

}
