/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.scoping;

import dk.sdu.mdsd.scoping.AbstractMathInterpreterScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MathInterpreterScopeProvider extends AbstractMathInterpreterScopeProvider {
}
