/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mdsd.ide.contentassist.antlr.internal.InternalMathInterpreterParser;
import dk.sdu.mdsd.services.MathInterpreterGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathInterpreterParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathInterpreterGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathInterpreterGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPlusOrMinusAccess().getAlternatives_1(), "rule__PlusOrMinus__Alternatives_1");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getAlternatives_1(), "rule__MultiplyOrDivide__Alternatives_1");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getSolutionAccess().getGroup(), "rule__Solution__Group__0");
			builder.put(grammarAccess.getSolutionAccess().getGroup_0(), "rule__Solution__Group_0__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup(), "rule__PlusOrMinus__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0(), "rule__PlusOrMinus__Group_1_0__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_1(), "rule__PlusOrMinus__Group_1_1__0");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getGroup(), "rule__MultiplyOrDivide__Group__0");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getGroup_1_0(), "rule__MultiplyOrDivide__Group_1_0__0");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getGroup_1_1(), "rule__MultiplyOrDivide__Group_1_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_2(), "rule__Primary__Group_2__0");
			builder.put(grammarAccess.getSolutionAccess().getVariablesAssignment_0_1(), "rule__Solution__VariablesAssignment_0_1");
			builder.put(grammarAccess.getSolutionAccess().getExpressionAssignment_2(), "rule__Solution__ExpressionAssignment_2");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_0(), "rule__Variable__NameAssignment_0");
			builder.put(grammarAccess.getVariableAccess().getValueAssignment_2(), "rule__Variable__ValueAssignment_2");
			builder.put(grammarAccess.getExpressionAccess().getExpAssignment(), "rule__Expression__ExpAssignment");
			builder.put(grammarAccess.getPlusOrMinusAccess().getLeftAssignment_0(), "rule__PlusOrMinus__LeftAssignment_0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOperatorAssignment_1_0_1(), "rule__PlusOrMinus__OperatorAssignment_1_0_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getRightAssignment_1_0_2(), "rule__PlusOrMinus__RightAssignment_1_0_2");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOperatorAssignment_1_1_1(), "rule__PlusOrMinus__OperatorAssignment_1_1_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getRightAssignment_1_1_2(), "rule__PlusOrMinus__RightAssignment_1_1_2");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getLeftAssignment_0(), "rule__MultiplyOrDivide__LeftAssignment_0");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getOperatorAssignment_1_0_1(), "rule__MultiplyOrDivide__OperatorAssignment_1_0_1");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getRightAssignment_1_0_2(), "rule__MultiplyOrDivide__RightAssignment_1_0_2");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getOperatorAssignment_1_1_1(), "rule__MultiplyOrDivide__OperatorAssignment_1_1_1");
			builder.put(grammarAccess.getMultiplyOrDivideAccess().getRightAssignment_1_1_2(), "rule__MultiplyOrDivide__RightAssignment_1_1_2");
			builder.put(grammarAccess.getPrimaryAccess().getValueAssignment_0_1(), "rule__Primary__ValueAssignment_0_1");
			builder.put(grammarAccess.getPrimaryAccess().getValueAssignment_1_1(), "rule__Primary__ValueAssignment_1_1");
			builder.put(grammarAccess.getPrimaryAccess().getValueAssignment_2_2(), "rule__Primary__ValueAssignment_2_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathInterpreterGrammarAccess grammarAccess;

	@Override
	protected InternalMathInterpreterParser createParser() {
		InternalMathInterpreterParser result = new InternalMathInterpreterParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathInterpreterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathInterpreterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
