/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.mathInterpreter.impl;

import dk.sdu.mdsd.mathInterpreter.Divide;
import dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Divide</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DivideImpl extends MultiplyOrDivideImpl implements Divide
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DivideImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathInterpreterPackage.Literals.DIVIDE;
  }

} //DivideImpl
