/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathInterpreterValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.sdu.mdsd.mathInterpreter.MathInterpreterPackage.eINSTANCE);
		return result;
	}
}
