/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mdsd.MathInterpreterRuntimeModule;
import dk.sdu.mdsd.MathInterpreterStandaloneSetup;
import dk.sdu.mdsd.ide.MathInterpreterIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathInterpreterIdeSetup extends MathInterpreterStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathInterpreterRuntimeModule _mathInterpreterRuntimeModule = new MathInterpreterRuntimeModule();
    MathInterpreterIdeModule _mathInterpreterIdeModule = new MathInterpreterIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathInterpreterRuntimeModule, _mathInterpreterIdeModule));
  }
}
